# 异常


- 异常事件分为两类：
*	Error:JVM无法解决的问题，如JVM内部错误，资源耗尽。也称为运行时异常。
*	Exception：空指针访问，试图读取不存在的文件，数组越界，网络连接中断。也称为编译时异常。
- 使用try将可能出现异常的代码进行包装，执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，在catch中进行匹配。一旦处理完成，就会跳出try-catch块，继续执行后面的代码。
- 在try结构中声明的变量，在出了try结构之后，就不能再调用。可以实现声明一个初值。
- finally中声明的是一定可以执行的代码，即使try和catch中存在return语句，catch中也出现异常。
- 垃圾回收机制只回收JVM堆内存里的空间，对其他物理连接，比如数据库连接，输入输出流，Socket连接确无能为力。此时的资源释放，就需要声明在finally语句块中。
- 使用try-catch-finally处理编译时异常，使得程序在编译时不再报错，但运行时依然报错，是将一个编译时可能出现的异常延迟到运行时出现。
- 异常处理：throws+异常类型 写在方法的声明处，指明此代码执行时，可能会抛出的异常类型。一旦方法体执行，出现异常，仍会生成一个异常类的对象。throws的方式只是将异常抛给了方法的调用者，并没有将异常真正处理掉。其中子类重写的方法抛出的异常类型不大于父类被重写的方法被抛出的异常类型。
- 如果父类中被重写的方法没有throws方式处理异常，则子类中重写的方法也不能使用throws，意味着如果子类重写的方法中异常，必须使用try-catch处理。而执行的方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行，则这几个方法可以使用throws进行处理，而执行方法a可以使用try-catch方法。
- 可以使用throw new Exception进行手动抛出异常，在方法的声明处在进行throws处理，在主程序处用try-catch处理。
- 自定义异常类：继承于现有的异常结构，RuntimeException,Exception，提供一个全局常量，static final long serialVersionUID。提供重载的构造器。
- throws和throw的区别：
  *	throws用在方法声明后面,表示抛出异常，由方法的调用者即上一级来处理，而throw用在方法体内，用来制造一个异常。
  *	throws是声明该异常，以便调用者去捕捉该异常，而throw是直接抛出异常实例。
  *	throws表示异常出现的一种可能性，而throw就表示一定会出现该异常。
